### ISSUE TITLE
How to integrate EC2 Spot Instance interruption notice

### ISSUE THREAD

**Issue by eugenbg** [nginxinc/nginx-asg-sync#277]
Hello,

we are using aws spot instances with nginx plus, is there an easy way to make use of the interruption notices to exclude instances from an upstream group?

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html

thank you

**Comment by brianehlert** [comment]
It is theoretically possible that through watching the cloud API the instance state change to "terminating" (or the transitional state that happens prior to terminating) can be identified and an upstream put into a down state - which tells nginx to stop forwarding traffic but keeps the upstream in the group.
The second possibility is to simply remove the server from the upstream group prior to it being "terminated" (instead of tagging it as "down").  

The states are common for all EC2 for machine instances and not spot instance specific.  It would make the behavior stronger - at least that is how I would look at implementing it, in a universal way for scale groups regardless of the instance type.

It appears that the project does already respond in this way.  From the readme:
Note: because the asg-sync works on a polling-based model, there will be a delay between the instance going to a terminating state and the asg-sync removing its IP from NGINX Plus. To guarantee that NGINX Plus doesn't send any requests to a terminated instance, make sure the instance goes to the Terminating:Wait state for a period greater than the interval sync_interval_in_seconds.

Is tuning the current behavior not adequate for your situation?
